[package]
name = "raytrace"
version = "0.1.0"
authors = ["Connor Hewitt <connor.hewitt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.15.0"
derive_more = "0.99.0"